# Generated by Django 6.0.5 on 2026-07-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('new', 'Nouveau'), ('popular', 'Populaire'), ('promo', 'Promo'), ('spicy', 'Épicé'), ('veggie', 'Végé')], default='', max_length=10, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat (XAF)"),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, verbose_name="Seuil d'alerte stock"),
        ),
        migrations.AddField(
            model_name='item',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix promo (XAF)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de vente (XAF)'),
        ),
    ]
