# Generated by Django 6.0.5 on 2026-07-03 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_item_badge_item_cost_price_item_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial', models.BooleanField(default=True, verbose_name='Essai gratuit')),
                ('suspended', models.BooleanField(default=False, verbose_name='Suspendu')),
                ('current_period_end', models.DateField(blank=True, null=True, verbose_name="Payé jusqu'au")),
                ('price', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Prix mensuel (XAF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='inventory.bar')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('method', models.CharField(default='manuel', max_length=30)),
                ('note', models.CharField(blank=True, default='', max_length=160)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='inventory.bar')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
