# Generated by Django 6.0.5 on 2026-07-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_backfill_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(blank=True, default='', max_length=40)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='inventory.bar')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['bar', 'ts'], name='inventory_m_bar_id_ba9373_idx')],
            },
        ),
    ]
