# Generated by Django 6.0.5 on 2026-07-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_menuscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Couleur du menu client, ex. #ff7a18. Laisser vide = orange BUUB.', max_length=7, verbose_name="Couleur d'accent du menu"),
        ),
        migrations.AddField(
            model_name='bar',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Bannière du menu'),
        ),
    ]
