# Generated by Django 6.0.5 on 2026-07-06 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_bar_accent_color_bar_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Image de publicité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='inventory.bar')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
